import uuid
from fastapi import APIRouter, HTTPException, Query
from backend.database import get_db_cursor
from backend.schemas.recommendation import (
    BlockRecommendationCreate,
    BlockRecommendationResponse,
    ApprovalAction,
)
from optimizer.scheduler import optimize_block_schedule

router = APIRouter(prefix="/recommendations", tags=["Recommendations"])


@router.get("", response_model=list[BlockRecommendationResponse])
def get_all_recommendations(
    status: str | None = Query(None, description="Filter by status (PENDING, APPROVED, REJECTED)")
):
    """Returns all block recommendations generated by the optimizer."""
    with get_db_cursor() as cur:
        if status:
            cur.execute(
                "SELECT * FROM block_recommendations WHERE status = %s ORDER BY created_at DESC;",
                (status.upper(),)
            )
        else:
            cur.execute("SELECT * FROM block_recommendations ORDER BY created_at DESC;")
        rows = cur.fetchall()
        return [BlockRecommendationResponse(**row) for row in rows]


@router.post("/optimize", response_model=list[BlockRecommendationResponse])
def run_optimization():
    """
    Triggers the CP-SAT Optimizer.
    Pulls pending maintenance requests, train timetable slots, and crews from PostgreSQL.
    Computes optimal possession windows avoiding train collisions and bundling cross-department work.
    Persists and returns the generated block recommendations.
    """
    with get_db_cursor() as cur:
        # 1. Fetch pending maintenance requests
        cur.execute("SELECT * FROM maintenance_requests WHERE status = 'PENDING';")
        requests = cur.fetchall()
        if not requests:
            return []

        # 2. Fetch train timetables
        cur.execute("SELECT * FROM timetable_slots;")
        timetable = cur.fetchall()

        # 3. Fetch crews
        cur.execute("SELECT * FROM crews WHERE available = TRUE;")
        crews = cur.fetchall()

        # 4. Execute CP-SAT optimizer
        recs = optimize_block_schedule(
            requests=[dict(r) for r in requests],
            timetable=[dict(t) for t in timetable],
            crews=[dict(c) for c in crews],
        )

        saved_recs = []
        for rec in recs:
            query = """
            INSERT INTO block_recommendations (
                recommendation_id, track_id, start_time, end_time, duration_minutes,
                participating_departments, maintenance_request_ids, expected_delay_minutes,
                status, reasons
            ) VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
            )
            ON CONFLICT (recommendation_id) DO UPDATE SET
                start_time = EXCLUDED.start_time,
                end_time = EXCLUDED.end_time,
                duration_minutes = EXCLUDED.duration_minutes,
                participating_departments = EXCLUDED.participating_departments,
                maintenance_request_ids = EXCLUDED.maintenance_request_ids,
                reasons = EXCLUDED.reasons
            RETURNING *;
            """
            cur.execute(
                query,
                (
                    rec["recommendation_id"],
                    rec["track_id"],
                    rec["start_time"],
                    rec["end_time"],
                    rec["duration_minutes"],
                    rec["participating_departments"],
                    rec["maintenance_request_ids"],
                    rec["expected_delay_minutes"],
                    rec["status"],
                    rec["reasons"],
                ),
            )
            row = cur.fetchone()
            saved_recs.append(BlockRecommendationResponse(**row))

        return saved_recs


@router.get("/{recommendation_id}", response_model=BlockRecommendationResponse)
def get_recommendation_by_id(recommendation_id: str):
    """Returns details for a single block recommendation."""
    with get_db_cursor() as cur:
        cur.execute("SELECT * FROM block_recommendations WHERE recommendation_id = %s;", (recommendation_id,))
        row = cur.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail=f"Recommendation '{recommendation_id}' not found")
        return BlockRecommendationResponse(**row)


@router.post("", response_model=BlockRecommendationResponse, status_code=201)
def create_recommendation(rec: BlockRecommendationCreate):
    """Stores a block recommendation manually."""
    rec_id = rec.recommendation_id or f"REC-{uuid.uuid4().hex[:8].upper()}"
    query = """
    INSERT INTO block_recommendations (
        recommendation_id, track_id, start_time, end_time, duration_minutes,
        participating_departments, maintenance_request_ids, expected_delay_minutes,
        status, reasons
    ) VALUES (
        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
    ) RETURNING *;
    """
    with get_db_cursor() as cur:
        cur.execute(
            query,
            (
                rec_id,
                rec.track_id,
                rec.start_time,
                rec.end_time,
                rec.duration_minutes,
                rec.participating_departments,
                rec.maintenance_request_ids,
                rec.expected_delay_minutes,
                rec.status.upper(),
                rec.reasons,
            ),
        )
        row = cur.fetchone()
        return BlockRecommendationResponse(**row)


@router.post("/{recommendation_id}/approve", response_model=BlockRecommendationResponse)
def approve_recommendation(recommendation_id: str, action: ApprovalAction | None = None):
    """
    Controller approves the recommended maintenance block.
    Marks the recommendation as APPROVED and updates associated maintenance requests to SCHEDULED.
    """
    with get_db_cursor() as cur:
        cur.execute(
            """
            UPDATE block_recommendations
            SET status = 'APPROVED'
            WHERE recommendation_id = %s
            RETURNING *;
            """,
            (recommendation_id,),
        )
        row = cur.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail=f"Recommendation '{recommendation_id}' not found")

        # Update associated maintenance requests to SCHEDULED
        req_ids = row.get("maintenance_request_ids") or []
        if req_ids:
            cur.execute(
                """
                UPDATE maintenance_requests
                SET status = 'SCHEDULED'
                WHERE request_id = ANY(%s);
                """,
                (req_ids,)
            )

        return BlockRecommendationResponse(**row)


@router.post("/{recommendation_id}/reject", response_model=BlockRecommendationResponse)
def reject_recommendation(recommendation_id: str, action: ApprovalAction | None = None):
    """
    Controller rejects the recommended maintenance block.
    Marks the recommendation as REJECTED.
    """
    with get_db_cursor() as cur:
        cur.execute(
            """
            UPDATE block_recommendations
            SET status = 'REJECTED'
            WHERE recommendation_id = %s
            RETURNING *;
            """,
            (recommendation_id,),
        )
        row = cur.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail=f"Recommendation '{recommendation_id}' not found")
        return BlockRecommendationResponse(**row)
