import type {
  AIRecommendation,
  RiskDistributionItem,
  PriorityScoreFactor,
  TimelineEventItem,
  WhatIfScenario,
  PotentialImpactStat,
} from "./types";

export const INITIAL_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: "REC-101",
    title: "Combine 3 maintenance activities in Corridor C-01",
    description: "Track renewal, OHE catenary sag adjustment, and axle counter calibration can bundle into a single 4-hour possession window on 14 Sep.",
    impact: "High",
    confidence: 94,
    time: "2 hours ago",
    department: "Multi-Department",
    departmentCode: "engineering",
    corridor: "C-01 (Delhi - Agra)",
    suggestedAction: "Schedule in AI Planner",
    recommendedWindow: "14:00 – 18:00 (14 Sep)",
    applied: true,
  },
  {
    id: "REC-102",
    title: "Track Section T-102 requires urgent ultrasonic testing",
    description: "AI predictive degradation model flagged an accelerated micro-fissure rate. Failure risk increased from 72% to 87% over 48 hours.",
    impact: "Critical",
    confidence: 91,
    time: "4 hours ago",
    department: "Track & Civil",
    departmentCode: "engineering",
    corridor: "C-02 (Aligarh - Kanpur)",
    suggestedAction: "Create Work Order",
    recommendedWindow: "Immediate (Next window)",
    applied: false,
  },
  {
    id: "REC-103",
    title: "Schedule OHE tension inspection in low-traffic window",
    description: "Corridor C-03 has a 5-hour low passenger & freight headway on 15 Sep between 11:00 and 16:00. Ideal for tower wagon deployment.",
    impact: "Medium",
    confidence: 87,
    time: "6 hours ago",
    department: "Electrical / OHE",
    departmentCode: "electrical",
    corridor: "C-03 (Lucknow - Varanasi)",
    suggestedAction: "Reserve Corridor Window",
    recommendedWindow: "11:00 – 16:00 (15 Sep)",
    applied: false,
  },
  {
    id: "REC-104",
    title: "Reschedule 2 freight paths to avoid maintenance conflict",
    description: "Freight runs F-204 and F-208 conflict with emergency turnout point motor testing at Agra Junction Yard.",
    impact: "Medium",
    confidence: 83,
    time: "1 day ago",
    department: "Operations & Traffic",
    departmentCode: "traffic",
    corridor: "C-01 (Delhi - Agra)",
    suggestedAction: "Re-route Goods Train",
    recommendedWindow: "Adjust headway by +35 mins",
    applied: false,
  },
  {
    id: "REC-105",
    title: "Optimize crew deployment for Track Tamping in C-02",
    description: "Shifting Tamper Machine Team Bravo from Kanpur Depot avoids 3.5 hours of dead-head transit time and eliminates crew overtime.",
    impact: "Low",
    confidence: 78,
    time: "1 day ago",
    department: "Track & Civil",
    departmentCode: "engineering",
    corridor: "C-02 (Aligarh - Kanpur)",
    suggestedAction: "Reallocate Crew Depot",
    recommendedWindow: "Shift start 07:00",
    applied: false,
  },
  {
    id: "REC-106",
    title: "Point Motor PM-401 showing high electrical resistance",
    description: "SMMS telemetry indicates motor operating current spiked to 4.2A (normal: 2.8A). Recommended lubrication and contact cleaning.",
    impact: "Critical",
    confidence: 96,
    time: "1 day ago",
    department: "Signaling & Telecom",
    departmentCode: "snt",
    corridor: "C-04 (Varanasi - Prayagraj)",
    suggestedAction: "Dispatch S&T Rapid Team",
    recommendedWindow: "Within 24 hours",
    applied: false,
  },
];

export const RISK_DISTRIBUTION: RiskDistributionItem[] = [
  { level: "Critical", count: 62, percentage: 5, color: "bg-destructive" },
  { level: "High", count: 224, percentage: 18, color: "bg-orange-500" },
  { level: "Medium", count: 399, percentage: 32, color: "bg-amber-400" },
  { level: "Low", count: 563, percentage: 45, color: "bg-emerald-500" },
];

export const PRIORITY_FACTORS: PriorityScoreFactor[] = [
  { label: "Failure Risk Probability", score: "28 / 30", percentage: 93, weight: "30%" },
  { label: "Asset Criticality Index", score: "18 / 20", percentage: 90, weight: "20%" },
  { label: "Overdue Maintenance Urgency", score: "14 / 15", percentage: 93, weight: "15%" },
  { label: "Network Availability Impact", score: "15 / 20", percentage: 75, weight: "20%" },
  { label: "Train Traffic Density Impact", score: "7 / 10", percentage: 70, weight: "10%" },
  { label: "Historical Breakdown Frequency", score: "8 / 10", percentage: 80, weight: "10%" },
];

export const TIMELINE_EVENTS: TimelineEventItem[] = [
  {
    id: "EV-1",
    time: "2 hours ago",
    title: "Multi-Agent Block Coordinated",
    description: "CP-SAT engine successfully consolidated 3 department tasks into C-01 window.",
    agent: "Optimization Agent",
    type: "success",
  },
  {
    id: "EV-2",
    time: "4 hours ago",
    title: "Critical Track Risk Flagged",
    description: "TMS defect sync elevated T-102 rail wear risk to 87%. Alert pushed to Engineering.",
    agent: "Track Agent",
    type: "critical",
  },
  {
    id: "EV-3",
    time: "6 hours ago",
    title: "Goods Train Forecast Re-analyzed",
    description: "COA timetable integration identified low-traffic gap on 14 Sep (14:00 - 18:00).",
    agent: "Traffic Agent",
    type: "info",
  },
  {
    id: "EV-4",
    time: "1 day ago",
    title: "Predictive Health Model Retrained",
    description: "Gradient Boosted Tree model converged on 14,800 sensor telemetry records.",
    agent: "ML Engine",
    type: "info",
  },
  {
    id: "EV-5",
    time: "2 days ago",
    title: "OHE Tension Drift Compensated",
    description: "Temperature-adjusted sag threshold triggered preventive inspection recommendation.",
    agent: "Electrical Agent",
    type: "warning",
  },
];

export const WHAT_IF_SCENARIOS: WhatIfScenario[] = [
  {
    id: "SCEN-1",
    name: "Cross-Department Bundling (Current Optimal)",
    description: "Co-schedules Track, OHE, and S&T tasks within a single possession corridor window.",
    downtimeSaved: "6.2 hours",
    availabilityDelta: "+7.8%",
    trainConflicts: 0,
    score: 94,
    corridor: "C-01",
  },
  {
    id: "SCEN-2",
    name: "Heavy Monsoon Pre-caution Slow Order",
    description: "Simulates ballast saturation and speeds capped at 75 km/h across C-02 & C-03.",
    downtimeSaved: "2.1 hours",
    availabilityDelta: "-3.4%",
    trainConflicts: 2,
    score: 79,
    corridor: "C-02 & C-03",
  },
  {
    id: "SCEN-3",
    name: "Peak Freight Corridor Surge (+35% Goods)",
    description: "Evaluates impact of 14 additional coal & container freight trains from Dadri DFC.",
    downtimeSaved: "3.8 hours",
    availabilityDelta: "+2.1%",
    trainConflicts: 1,
    score: 83,
    corridor: "C-01 & C-02",
  },
  {
    id: "SCEN-4",
    name: "Track Machine Failure Fallback",
    description: "Models manual tamping substitution when Tamping Machine Plasser-09 is in depot repair.",
    downtimeSaved: "1.4 hours",
    availabilityDelta: "-1.8%",
    trainConflicts: 0,
    score: 74,
    corridor: "C-03",
  },
];

export const POTENTIAL_IMPACT_STATS: PotentialImpactStat[] = [
  {
    label: "Total Downtime Saved",
    value: "6.2 hours",
    change: "+28% efficiency",
    positive: true,
    iconName: "clock",
  },
  {
    label: "Redundant Blocks Avoided",
    value: "3 blocks",
    change: "+50% bundled",
    positive: true,
    iconName: "train",
  },
  {
    label: "Fixed Asset Availability",
    value: "+7.8%",
    change: "+2.1% net gain",
    positive: true,
    iconName: "shield",
  },
  {
    label: "Projected Cost Avoidance",
    value: "₹12.4 Lakhs",
    change: "+18% savings",
    positive: true,
    iconName: "currency",
  },
];
