import { MaintenanceBlock, PlanKPIData } from "./types";

export const initialPlanKPIs: PlanKPIData = {
  totalTasks: 22,
  tasksTrend: "+20% from last week",
  scheduledBlocks: 7,
  blocksTrend: "-12% possession downtime",
  corridorsCount: 4,
  departmentsCount: 3,
  resourceUtilization: 91,
  utilizationTrend: "+6% from last week",
};

export const weekDates = [
  { shortDate: "14 Sep", day: "Sun", fullDate: "14 Sep 2025" },
  { shortDate: "15 Sep", day: "Mon", fullDate: "15 Sep 2025" },
  { shortDate: "16 Sep", day: "Tue", fullDate: "16 Sep 2025" },
  { shortDate: "17 Sep", day: "Wed", fullDate: "17 Sep 2025" },
  { shortDate: "18 Sep", day: "Thu", fullDate: "18 Sep 2025" },
  { shortDate: "19 Sep", day: "Fri", fullDate: "19 Sep 2025" },
  { shortDate: "20 Sep", day: "Sat", fullDate: "20 Sep 2025" },
];

export const corridorMetadata = [
  { id: "C-01", name: "Delhi – Agra", trackType: "High Speed Mainline", maxSpeed: 160 },
  { id: "C-02", name: "Agra – Gwalior", trackType: "Double Line Electrified", maxSpeed: 130 },
  { id: "C-03", name: "Gwalior – Jhansi", trackType: "Heavy Freight & Passenger", maxSpeed: 130 },
  { id: "C-04", name: "Jhansi – Bina", trackType: "Triple Line Feeder", maxSpeed: 120 },
];

export const initialBlocks: MaintenanceBlock[] = [
  {
    id: 1,
    blockCode: "BLK-2025-0914-01",
    date: "14 Sep 2025",
    shortDate: "14 Sep",
    day: "Sun",
    startTime: "11:00",
    endTime: "15:00",
    durationHours: 4.0,
    corridorId: "C-01",
    corridorName: "Delhi – Agra",
    tasksCount: 5,
    departments: ["Engineering", "OHE", "S&T"],
    trainImpactSummary: "0 trains impacted",
    trainsRegulated: 0,
    aiScore: 94,
    status: "AI Suggested",
    blockType: "Full Possession",
    weather: "Clear (28°C, Wind 6 km/h)",
    crewMembers: 16,
    safetySupervised: true,
    downtimeSavedHours: 6.0,
    availabilityGainPercent: 7.8,
    costSavingsLakhs: 12.4,
    assignedCrew: "Joint Sectional Gang #4 (Northern Division)",
    assignedMachines: ["CSM-952 (Continuous Tamping)", "Tower Wagon TW-04", "USFD Rail Trolley #2"],
    tasks: [
      {
        id: "TSK-ENG-101",
        title: "High-speed switch cross-over tamping & ballast dressing",
        department: "Engineering",
        sectionKm: "KM 124.2 - 126.8",
        priority: "Critical",
        durationMinutes: 180,
        equipment: "CSM-952 Track Tamper",
        crewRequired: 6,
      },
      {
        id: "TSK-OHE-204",
        title: "Catenary droppers tension check & insulator washing",
        department: "OHE",
        sectionKm: "KM 124.0 - 127.0",
        priority: "High",
        durationMinutes: 120,
        equipment: "Tower Wagon TW-04",
        crewRequired: 4,
      },
      {
        id: "TSK-SNT-309",
        title: "Digital Axle Counter head alignment & track circuit check",
        department: "S&T",
        sectionKm: "KM 125.1",
        priority: "High",
        durationMinutes: 90,
        equipment: "Calibration Kit & Multi-tester",
        crewRequired: 3,
      },
      {
        id: "TSK-ENG-108",
        title: "Fishplate bolt torquing and weld collar visual inspection",
        department: "Engineering",
        sectionKm: "KM 125.8",
        priority: "Medium",
        durationMinutes: 60,
        equipment: "Hydraulic Torque Wrench",
        crewRequired: 2,
      },
      {
        id: "TSK-SNT-315",
        title: "Point Machine 42A lubrication & stroke test",
        department: "S&T",
        sectionKm: "KM 126.2",
        priority: "Medium",
        durationMinutes: 45,
        equipment: "Point Machine Tester",
        crewRequired: 2,
      },
    ],
    affectedTrains: [
      {
        trainNo: "12002",
        trainName: "Bhopal Shatabdi",
        trainType: "Express",
        scheduledTime: "10:42",
        impactType: "None",
        delayMinutes: 0,
        notes: "Passed section prior to block possession handover.",
      },
      {
        trainNo: "12628",
        trainName: "Karnataka Express",
        trainType: "Superfast",
        scheduledTime: "15:25",
        impactType: "None",
        delayMinutes: 0,
        notes: "Scheduled arrival 25 mins after track clearance.",
      },
    ],
  },
  {
    id: 2,
    blockCode: "BLK-2025-0914-02",
    date: "14 Sep 2025",
    shortDate: "14 Sep",
    day: "Sun",
    startTime: "15:00",
    endTime: "18:00",
    durationHours: 3.0,
    corridorId: "C-03",
    corridorName: "Gwalior – Jhansi",
    tasksCount: 2,
    departments: ["OHE", "Engineering"],
    trainImpactSummary: "1 train regulated",
    trainsRegulated: 1,
    aiScore: 86,
    status: "AI Suggested",
    blockType: "Power Disconnection Only",
    weather: "Partly Cloudy (31°C)",
    crewMembers: 10,
    safetySupervised: true,
    downtimeSavedHours: 4.5,
    availabilityGainPercent: 5.2,
    costSavingsLakhs: 8.6,
    assignedCrew: "OHE Sub-Depot Gang Gwalior",
    assignedMachines: ["Tower Wagon TW-08", "Ballast Regulator BR-12"],
    tasks: [
      {
        id: "TSK-OHE-220",
        title: "Feeder wire bracket replacement & contact wire micrometer profiling",
        department: "OHE",
        sectionKm: "KM 342.1 - 344.5",
        priority: "High",
        durationMinutes: 140,
        equipment: "Tower Wagon TW-08",
        crewRequired: 6,
      },
      {
        id: "TSK-ENG-119",
        title: "Ballast profiling and shoulder consolidation",
        department: "Engineering",
        sectionKm: "KM 343.0 - 344.0",
        priority: "Medium",
        durationMinutes: 110,
        equipment: "Ballast Regulator BR-12",
        crewRequired: 4,
      },
    ],
    affectedTrains: [
      {
        trainNo: "BOXN-7881",
        trainName: "Coal Rake (Thermal Plant)",
        trainType: "Freight",
        scheduledTime: "16:20",
        impactType: "Regulated",
        delayMinutes: 14,
        notes: "Loop regulation at Datia loop siding for 14 minutes; within COA tolerance.",
      },
    ],
  },
  {
    id: 3,
    blockCode: "BLK-2025-0915-01",
    date: "15 Sep 2025",
    shortDate: "15 Sep",
    day: "Mon",
    startTime: "10:00",
    endTime: "13:00",
    durationHours: 3.0,
    corridorId: "C-02",
    corridorName: "Agra – Gwalior",
    tasksCount: 3,
    departments: ["S&T", "Engineering"],
    trainImpactSummary: "0 trains impacted",
    trainsRegulated: 0,
    aiScore: 89,
    status: "AI Suggested",
    blockType: "Full Possession",
    weather: "Sunny (29°C)",
    crewMembers: 11,
    safetySupervised: true,
    downtimeSavedHours: 3.8,
    availabilityGainPercent: 6.1,
    costSavingsLakhs: 9.8,
    assignedCrew: "S&T Field Unit Dholpur + Track Gang #8",
    assignedMachines: ["UNIMAT-08 Switch Tamper"],
    tasks: [
      {
        id: "TSK-SNT-324",
        title: "Electronic Interlocking (EI) loop module software diagnostic",
        department: "S&T",
        sectionKm: "KM 218.4 (Dholpur Yard)",
        priority: "Critical",
        durationMinutes: 110,
        equipment: "EI Simulator Diagnostic Tool",
        crewRequired: 4,
      },
      {
        id: "TSK-ENG-128",
        title: "Turnout 101B tongue rail gap adjustment and sleeper packing",
        department: "Engineering",
        sectionKm: "KM 218.5",
        priority: "High",
        durationMinutes: 90,
        equipment: "Hydraulic Lifting Jacks",
        crewRequired: 5,
      },
      {
        id: "TSK-ENG-134",
        title: "Glued insulated rail joint (GJ) ultrasonic testing",
        department: "Engineering",
        sectionKm: "KM 219.0",
        priority: "Medium",
        durationMinutes: 60,
        equipment: "USFD Trolley",
        crewRequired: 2,
      },
    ],
    affectedTrains: [
      {
        trainNo: "12722",
        trainName: "Dakshin Express",
        trainType: "Express",
        scheduledTime: "09:35",
        impactType: "None",
        delayMinutes: 0,
        notes: "Timely corridor clearance verified in COA simulation.",
      },
    ],
  },
  {
    id: 4,
    blockCode: "BLK-2025-0916-01",
    date: "16 Sep 2025",
    shortDate: "16 Sep",
    day: "Tue",
    startTime: "12:00",
    endTime: "16:00",
    durationHours: 4.0,
    corridorId: "C-01",
    corridorName: "Delhi – Agra",
    tasksCount: 4,
    departments: ["Engineering", "OHE"],
    trainImpactSummary: "2 trains regulated",
    trainsRegulated: 2,
    aiScore: 78,
    status: "Pending Review",
    blockType: "Full Possession",
    weather: "Overcast (27°C, 30% rain chance)",
    crewMembers: 14,
    safetySupervised: true,
    downtimeSavedHours: 5.0,
    availabilityGainPercent: 4.8,
    costSavingsLakhs: 7.5,
    assignedCrew: "Mathura Track Division + OHE Gang",
    assignedMachines: ["BCM-303 Ballast Cleaner", "Tower Wagon TW-02"],
    tasks: [
      {
        id: "TSK-ENG-142",
        title: "Deep screening of track ballast by BCM machine",
        department: "Engineering",
        sectionKm: "KM 98.4 - 100.2",
        priority: "Critical",
        durationMinutes: 200,
        equipment: "BCM-303 Ballast Cleaner",
        crewRequired: 8,
      },
      {
        id: "TSK-OHE-231",
        title: "Portal mast bracket realignment over screened section",
        department: "OHE",
        sectionKm: "KM 98.8 - 99.6",
        priority: "High",
        durationMinutes: 150,
        equipment: "Tower Wagon TW-02",
        crewRequired: 4,
      },
      {
        id: "TSK-ENG-149",
        title: "Fastener tightening and ERC toe load sampling",
        department: "Engineering",
        sectionKm: "KM 100.0",
        priority: "Medium",
        durationMinutes: 80,
        equipment: "Toe Load Measuring Gauge",
        crewRequired: 2,
      },
    ],
    affectedTrains: [
      {
        trainNo: "12156",
        trainName: "Bhopal Express",
        trainType: "Express",
        scheduledTime: "14:15",
        impactType: "Regulated",
        delayMinutes: 8,
        notes: "Regulated at Kosi Kalan for 8 mins, path recouped before Agra Cantt.",
      },
      {
        trainNo: "BCN-4490",
        trainName: "Fertilizer Freight Special",
        trainType: "Freight",
        scheduledTime: "15:00",
        impactType: "Regulated",
        delayMinutes: 18,
        notes: "Loop clearance at Chhata Station.",
      },
    ],
  },
  {
    id: 5,
    blockCode: "BLK-2025-0917-01",
    date: "17 Sep 2025",
    shortDate: "17 Sep",
    day: "Wed",
    startTime: "09:00",
    endTime: "12:00",
    durationHours: 3.0,
    corridorId: "C-04",
    corridorName: "Jhansi – Bina",
    tasksCount: 2,
    departments: ["OHE"],
    trainImpactSummary: "0 trains impacted",
    trainsRegulated: 0,
    aiScore: 82,
    status: "Pending Review",
    blockType: "Power Disconnection Only",
    weather: "Clear (26°C)",
    crewMembers: 8,
    safetySupervised: true,
    downtimeSavedHours: 3.0,
    availabilityGainPercent: 3.9,
    costSavingsLakhs: 5.2,
    assignedCrew: "Lalitpur Traction Substation Unit",
    assignedMachines: ["Tower Wagon TW-11"],
    tasks: [
      {
        id: "TSK-OHE-245",
        title: "Section insulator overhaul & sparkless neutral section test",
        department: "OHE",
        sectionKm: "KM 412.0 - 413.5",
        priority: "High",
        durationMinutes: 120,
        equipment: "Tower Wagon TW-11",
        crewRequired: 5,
      },
      {
        id: "TSK-OHE-250",
        title: "Earth wire bond connectivity verification",
        department: "OHE",
        sectionKm: "KM 412.8",
        priority: "Medium",
        durationMinutes: 45,
        equipment: "Ground Resistance Tester",
        crewRequired: 3,
      },
    ],
    affectedTrains: [
      {
        trainNo: "12616",
        trainName: "Grand Trunk Express",
        trainType: "Superfast",
        scheduledTime: "12:40",
        impactType: "None",
        delayMinutes: 0,
        notes: "Passes 40 mins after block de-energization canceled.",
      },
    ],
  },
  {
    id: 6,
    blockCode: "BLK-2025-0918-01",
    date: "18 Sep 2025",
    shortDate: "18 Sep",
    day: "Thu",
    startTime: "14:00",
    endTime: "16:00",
    durationHours: 2.0,
    corridorId: "C-04",
    corridorName: "Jhansi – Bina",
    tasksCount: 3,
    departments: ["Engineering", "S&T"],
    trainImpactSummary: "1 train regulated",
    trainsRegulated: 1,
    aiScore: 80,
    status: "Pending Review",
    blockType: "Full Possession",
    weather: "Clear (30°C)",
    crewMembers: 9,
    safetySupervised: true,
    downtimeSavedHours: 2.5,
    availabilityGainPercent: 4.1,
    costSavingsLakhs: 6.1,
    assignedCrew: "Bina Yard Maintenance Gang",
    assignedMachines: ["Hand-held Tamping Guns", "S&T Signal Scope"],
    tasks: [
      {
        id: "TSK-SNT-340",
        title: "Automatic Block Signal (ABS) aspect LED matrix replacement",
        department: "S&T",
        sectionKm: "KM 488.2",
        priority: "High",
        durationMinutes: 75,
        equipment: "Signal Testing Harness",
        crewRequired: 4,
      },
      {
        id: "TSK-ENG-162",
        title: "Transition curve track gauge realignment",
        department: "Engineering",
        sectionKm: "KM 488.0 - 489.0",
        priority: "Medium",
        durationMinutes: 80,
        equipment: "Track Gauge Gauge & Level",
        crewRequired: 5,
      },
    ],
    affectedTrains: [
      {
        trainNo: "BOXN-3312",
        trainName: "Empty Coal Goods Rake",
        trainType: "Freight",
        scheduledTime: "14:40",
        impactType: "Regulated",
        delayMinutes: 10,
        notes: "Speed restriction 30 km/h on adjacent down line.",
      },
    ],
  },
  {
    id: 7,
    blockCode: "BLK-2025-0919-01",
    date: "19 Sep 2025",
    shortDate: "19 Sep",
    day: "Fri",
    startTime: "10:00",
    endTime: "14:00",
    durationHours: 4.0,
    corridorId: "C-03",
    corridorName: "Gwalior – Jhansi",
    tasksCount: 3,
    departments: ["Engineering", "S&T"],
    trainImpactSummary: "0 trains impacted",
    trainsRegulated: 0,
    aiScore: 88,
    status: "Pending Review",
    blockType: "Full Possession",
    weather: "Pleasant (25°C)",
    crewMembers: 12,
    safetySupervised: true,
    downtimeSavedHours: 5.2,
    availabilityGainPercent: 6.5,
    costSavingsLakhs: 10.1,
    assignedCrew: "Gwalior Division Combined Track Squad",
    assignedMachines: ["CSM-910 Continuous Tamper", "USFD Ultrasonic Rig"],
    tasks: [
      {
        id: "TSK-ENG-175",
        title: "Weld collar ultrasonic testing & defect rail cut replacement",
        department: "Engineering",
        sectionKm: "KM 365.4",
        priority: "Critical",
        durationMinutes: 150,
        equipment: "Abrasive Rail Cutter & Welder",
        crewRequired: 6,
      },
      {
        id: "TSK-SNT-355",
        title: "Track circuit bonding & impedance bond tuning",
        department: "S&T",
        sectionKm: "KM 365.2 - 366.0",
        priority: "High",
        durationMinutes: 90,
        equipment: "Impedance Bond Calibrator",
        crewRequired: 3,
      },
      {
        id: "TSK-ENG-180",
        title: "Track alignment and tamping post rail replacement",
        department: "Engineering",
        sectionKm: "KM 365.0 - 366.0",
        priority: "Medium",
        durationMinutes: 90,
        equipment: "CSM-910 Track Tamper",
        crewRequired: 3,
      },
    ],
    affectedTrains: [
      {
        trainNo: "12804",
        trainName: "Swarna Jayanti Express",
        trainType: "Express",
        scheduledTime: "09:40",
        impactType: "None",
        delayMinutes: 0,
        notes: "Passed section prior to possession start.",
      },
    ],
  },
];
